id: I2106A439
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T10:59:09+00:00'
last_modified: '2022-06-08T09:47:12.149837+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4CZ294436
  title: ཀློང་སྙིང་བསྐྱེད་རྫོགས་རྫོགས་ཆེན་གསུམ་གྱི་འཁྲིད་ཡིག་དམར་བྱང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    20E9:
      image_group_id: I4CZ294545
      title: Volume 1 of klong snying bskyed rdzogs rdzogs chen gsum gyi 'khrid yig
        dmar byang /
      total_pages: 610
      order: 1
      base_file: 20E9.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
