id: P006982
initial_creation_type: ocr
source_metadata:
  id: bdr:W4CZ294436
  title: ཀློང་སྙིང་བསྐྱེད་རྫོགས་རྫོགས་ཆེན་གསུམ་གྱི་འཁྲིད་ཡིག་དམར་བྱང་།
  author: ''
  volumes:
    7bd4f00eee8b465d8fcf8da6ca11bf4b:
      image_group_id: I4CZ294545
      title: ''
      volume_number: 1
      total_pages: 610
ebook_metadata:
  title: ཀློང་སྙིང་བསྐྱེད་རྫོགས་རྫོགས་ཆེན་གསུམ་གྱི་འཁྲིད་ཡིག་དམར་བྱང་།
  author: ''
  sku: P006982
  cover: cover.jpg
  layers:
  - pagination
