id: P006982
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W4CZ294436
  title: ཀློང་སྙིང་བསྐྱེད་རྫོགས་རྫོགས་ཆེན་གསུམ་གྱི་འཁྲིད་ཡིག་དམར་བྱང་།
  author: ''
  volumes:
    16999e3c691a47298e6cb8c187e1c397:
      image_group_id: I4CZ294545
      title: Volume 1 of klong snying bskyed rdzogs rdzogs chen gsum gyi 'khrid yig
        dmar byang /
      volume_number: 1
      total_pages: 610
      base_file: v001.txt
